/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVehiclesRouteImport } from './routes/_app.vehicles'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppPurchasesRouteImport } from './routes/_app.purchases'
import { Route as AppFinancialRouteImport } from './routes/_app.financial'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppClientsRouteImport } from './routes/_app.clients'
import { Route as AppVehiclesIndexRouteImport } from './routes/_app.vehicles.index'
import { Route as AppSalesIndexRouteImport } from './routes/_app.sales.index'
import { Route as AppPurchasesIndexRouteImport } from './routes/_app.purchases.index'
import { Route as AppFinancialIndexRouteImport } from './routes/_app.financial.index'
import { Route as AppEmployeesIndexRouteImport } from './routes/_app.employees.index'
import { Route as AppClientsIndexRouteImport } from './routes/_app.clients.index'
import { Route as AppVehiclesNewRouteImport } from './routes/_app.vehicles.new'
import { Route as AppVehiclesIdRouteImport } from './routes/_app.vehicles.$id'
import { Route as AppSalesNewRouteImport } from './routes/_app.sales.new'
import { Route as AppSalesIdRouteImport } from './routes/_app.sales.$id'
import { Route as AppPurchasesNewRouteImport } from './routes/_app.purchases.new'
import { Route as AppPurchasesIdRouteImport } from './routes/_app.purchases.$id'
import { Route as AppFinancialTransactionsRouteImport } from './routes/_app.financial.transactions'
import { Route as AppFinancialBillsRouteImport } from './routes/_app.financial.bills'
import { Route as AppEmployeesNewRouteImport } from './routes/_app.employees.new'
import { Route as AppEmployeesIdRouteImport } from './routes/_app.employees.$id'
import { Route as AppClientsNewRouteImport } from './routes/_app.clients.new'
import { Route as AppClientsIdRouteImport } from './routes/_app.clients.$id'
import { Route as AppFinancialTransactionsIndexRouteImport } from './routes/_app.financial.transactions.index'
import { Route as AppVehiclesEditIdRouteImport } from './routes/_app.vehicles.edit.$id'
import { Route as AppFinancialTransactionsIdRouteImport } from './routes/_app.financial.transactions.$id'
import { Route as AppEmployeesEditIdRouteImport } from './routes/_app.employees.edit.$id'
import { Route as AppClientsEditIdRouteImport } from './routes/_app.clients.edit.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiclesRoute = AppVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancialRoute = AppFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiclesIndexRoute = AppVehiclesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVehiclesRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppPurchasesIndexRoute = AppPurchasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPurchasesRoute,
} as any)
const AppFinancialIndexRoute = AppFinancialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinancialRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppVehiclesNewRoute = AppVehiclesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppVehiclesRoute,
} as any)
const AppVehiclesIdRoute = AppVehiclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppVehiclesRoute,
} as any)
const AppSalesNewRoute = AppSalesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesIdRoute = AppSalesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppPurchasesNewRoute = AppPurchasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPurchasesRoute,
} as any)
const AppPurchasesIdRoute = AppPurchasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPurchasesRoute,
} as any)
const AppFinancialTransactionsRoute =
  AppFinancialTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AppFinancialRoute,
  } as any)
const AppFinancialBillsRoute = AppFinancialBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppFinancialRoute,
} as any)
const AppEmployeesNewRoute = AppEmployeesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppClientsNewRoute = AppClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppFinancialTransactionsIndexRoute =
  AppFinancialTransactionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppFinancialTransactionsRoute,
  } as any)
const AppVehiclesEditIdRoute = AppVehiclesEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AppVehiclesRoute,
} as any)
const AppFinancialTransactionsIdRoute =
  AppFinancialTransactionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppFinancialTransactionsRoute,
  } as any)
const AppEmployeesEditIdRoute = AppEmployeesEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppClientsEditIdRoute = AppClientsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AppClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/clients': typeof AppClientsRouteWithChildren
  '/employees': typeof AppEmployeesRouteWithChildren
  '/financial': typeof AppFinancialRouteWithChildren
  '/purchases': typeof AppPurchasesRouteWithChildren
  '/sales': typeof AppSalesRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/vehicles': typeof AppVehiclesRouteWithChildren
  '/clients/$id': typeof AppClientsIdRoute
  '/clients/new': typeof AppClientsNewRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/employees/new': typeof AppEmployeesNewRoute
  '/financial/bills': typeof AppFinancialBillsRoute
  '/financial/transactions': typeof AppFinancialTransactionsRouteWithChildren
  '/purchases/$id': typeof AppPurchasesIdRoute
  '/purchases/new': typeof AppPurchasesNewRoute
  '/sales/$id': typeof AppSalesIdRoute
  '/sales/new': typeof AppSalesNewRoute
  '/vehicles/$id': typeof AppVehiclesIdRoute
  '/vehicles/new': typeof AppVehiclesNewRoute
  '/clients/': typeof AppClientsIndexRoute
  '/employees/': typeof AppEmployeesIndexRoute
  '/financial/': typeof AppFinancialIndexRoute
  '/purchases/': typeof AppPurchasesIndexRoute
  '/sales/': typeof AppSalesIndexRoute
  '/vehicles/': typeof AppVehiclesIndexRoute
  '/clients/edit/$id': typeof AppClientsEditIdRoute
  '/employees/edit/$id': typeof AppEmployeesEditIdRoute
  '/financial/transactions/$id': typeof AppFinancialTransactionsIdRoute
  '/vehicles/edit/$id': typeof AppVehiclesEditIdRoute
  '/financial/transactions/': typeof AppFinancialTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/clients/new': typeof AppClientsNewRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/employees/new': typeof AppEmployeesNewRoute
  '/financial/bills': typeof AppFinancialBillsRoute
  '/purchases/$id': typeof AppPurchasesIdRoute
  '/purchases/new': typeof AppPurchasesNewRoute
  '/sales/$id': typeof AppSalesIdRoute
  '/sales/new': typeof AppSalesNewRoute
  '/vehicles/$id': typeof AppVehiclesIdRoute
  '/vehicles/new': typeof AppVehiclesNewRoute
  '/clients': typeof AppClientsIndexRoute
  '/employees': typeof AppEmployeesIndexRoute
  '/financial': typeof AppFinancialIndexRoute
  '/purchases': typeof AppPurchasesIndexRoute
  '/sales': typeof AppSalesIndexRoute
  '/vehicles': typeof AppVehiclesIndexRoute
  '/clients/edit/$id': typeof AppClientsEditIdRoute
  '/employees/edit/$id': typeof AppEmployeesEditIdRoute
  '/financial/transactions/$id': typeof AppFinancialTransactionsIdRoute
  '/vehicles/edit/$id': typeof AppVehiclesEditIdRoute
  '/financial/transactions': typeof AppFinancialTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/clients': typeof AppClientsRouteWithChildren
  '/_app/employees': typeof AppEmployeesRouteWithChildren
  '/_app/financial': typeof AppFinancialRouteWithChildren
  '/_app/purchases': typeof AppPurchasesRouteWithChildren
  '/_app/sales': typeof AppSalesRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/vehicles': typeof AppVehiclesRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/clients/$id': typeof AppClientsIdRoute
  '/_app/clients/new': typeof AppClientsNewRoute
  '/_app/employees/$id': typeof AppEmployeesIdRoute
  '/_app/employees/new': typeof AppEmployeesNewRoute
  '/_app/financial/bills': typeof AppFinancialBillsRoute
  '/_app/financial/transactions': typeof AppFinancialTransactionsRouteWithChildren
  '/_app/purchases/$id': typeof AppPurchasesIdRoute
  '/_app/purchases/new': typeof AppPurchasesNewRoute
  '/_app/sales/$id': typeof AppSalesIdRoute
  '/_app/sales/new': typeof AppSalesNewRoute
  '/_app/vehicles/$id': typeof AppVehiclesIdRoute
  '/_app/vehicles/new': typeof AppVehiclesNewRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/employees/': typeof AppEmployeesIndexRoute
  '/_app/financial/': typeof AppFinancialIndexRoute
  '/_app/purchases/': typeof AppPurchasesIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
  '/_app/vehicles/': typeof AppVehiclesIndexRoute
  '/_app/clients/edit/$id': typeof AppClientsEditIdRoute
  '/_app/employees/edit/$id': typeof AppEmployeesEditIdRoute
  '/_app/financial/transactions/$id': typeof AppFinancialTransactionsIdRoute
  '/_app/vehicles/edit/$id': typeof AppVehiclesEditIdRoute
  '/_app/financial/transactions/': typeof AppFinancialTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/clients'
    | '/employees'
    | '/financial'
    | '/purchases'
    | '/sales'
    | '/settings'
    | '/vehicles'
    | '/clients/$id'
    | '/clients/new'
    | '/employees/$id'
    | '/employees/new'
    | '/financial/bills'
    | '/financial/transactions'
    | '/purchases/$id'
    | '/purchases/new'
    | '/sales/$id'
    | '/sales/new'
    | '/vehicles/$id'
    | '/vehicles/new'
    | '/clients/'
    | '/employees/'
    | '/financial/'
    | '/purchases/'
    | '/sales/'
    | '/vehicles/'
    | '/clients/edit/$id'
    | '/employees/edit/$id'
    | '/financial/transactions/$id'
    | '/vehicles/edit/$id'
    | '/financial/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/'
    | '/clients/$id'
    | '/clients/new'
    | '/employees/$id'
    | '/employees/new'
    | '/financial/bills'
    | '/purchases/$id'
    | '/purchases/new'
    | '/sales/$id'
    | '/sales/new'
    | '/vehicles/$id'
    | '/vehicles/new'
    | '/clients'
    | '/employees'
    | '/financial'
    | '/purchases'
    | '/sales'
    | '/vehicles'
    | '/clients/edit/$id'
    | '/employees/edit/$id'
    | '/financial/transactions/$id'
    | '/vehicles/edit/$id'
    | '/financial/transactions'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/clients'
    | '/_app/employees'
    | '/_app/financial'
    | '/_app/purchases'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/vehicles'
    | '/_app/'
    | '/_app/clients/$id'
    | '/_app/clients/new'
    | '/_app/employees/$id'
    | '/_app/employees/new'
    | '/_app/financial/bills'
    | '/_app/financial/transactions'
    | '/_app/purchases/$id'
    | '/_app/purchases/new'
    | '/_app/sales/$id'
    | '/_app/sales/new'
    | '/_app/vehicles/$id'
    | '/_app/vehicles/new'
    | '/_app/clients/'
    | '/_app/employees/'
    | '/_app/financial/'
    | '/_app/purchases/'
    | '/_app/sales/'
    | '/_app/vehicles/'
    | '/_app/clients/edit/$id'
    | '/_app/employees/edit/$id'
    | '/_app/financial/transactions/$id'
    | '/_app/vehicles/edit/$id'
    | '/_app/financial/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vehicles': {
      id: '/_app/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AppVehiclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financial': {
      id: '/_app/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof AppFinancialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vehicles/': {
      id: '/_app/vehicles/'
      path: '/'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof AppVehiclesIndexRouteImport
      parentRoute: typeof AppVehiclesRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/purchases/': {
      id: '/_app/purchases/'
      path: '/'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AppPurchasesIndexRouteImport
      parentRoute: typeof AppPurchasesRoute
    }
    '/_app/financial/': {
      id: '/_app/financial/'
      path: '/'
      fullPath: '/financial/'
      preLoaderRoute: typeof AppFinancialIndexRouteImport
      parentRoute: typeof AppFinancialRoute
    }
    '/_app/employees/': {
      id: '/_app/employees/'
      path: '/'
      fullPath: '/employees/'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/_app/vehicles/new': {
      id: '/_app/vehicles/new'
      path: '/new'
      fullPath: '/vehicles/new'
      preLoaderRoute: typeof AppVehiclesNewRouteImport
      parentRoute: typeof AppVehiclesRoute
    }
    '/_app/vehicles/$id': {
      id: '/_app/vehicles/$id'
      path: '/$id'
      fullPath: '/vehicles/$id'
      preLoaderRoute: typeof AppVehiclesIdRouteImport
      parentRoute: typeof AppVehiclesRoute
    }
    '/_app/sales/new': {
      id: '/_app/sales/new'
      path: '/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof AppSalesNewRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/$id': {
      id: '/_app/sales/$id'
      path: '/$id'
      fullPath: '/sales/$id'
      preLoaderRoute: typeof AppSalesIdRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/purchases/new': {
      id: '/_app/purchases/new'
      path: '/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof AppPurchasesNewRouteImport
      parentRoute: typeof AppPurchasesRoute
    }
    '/_app/purchases/$id': {
      id: '/_app/purchases/$id'
      path: '/$id'
      fullPath: '/purchases/$id'
      preLoaderRoute: typeof AppPurchasesIdRouteImport
      parentRoute: typeof AppPurchasesRoute
    }
    '/_app/financial/transactions': {
      id: '/_app/financial/transactions'
      path: '/transactions'
      fullPath: '/financial/transactions'
      preLoaderRoute: typeof AppFinancialTransactionsRouteImport
      parentRoute: typeof AppFinancialRoute
    }
    '/_app/financial/bills': {
      id: '/_app/financial/bills'
      path: '/bills'
      fullPath: '/financial/bills'
      preLoaderRoute: typeof AppFinancialBillsRouteImport
      parentRoute: typeof AppFinancialRoute
    }
    '/_app/employees/new': {
      id: '/_app/employees/new'
      path: '/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof AppEmployeesNewRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/employees/$id': {
      id: '/_app/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/clients/new': {
      id: '/_app/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AppClientsNewRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/_app/clients/$id': {
      id: '/_app/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/_app/financial/transactions/': {
      id: '/_app/financial/transactions/'
      path: '/'
      fullPath: '/financial/transactions/'
      preLoaderRoute: typeof AppFinancialTransactionsIndexRouteImport
      parentRoute: typeof AppFinancialTransactionsRoute
    }
    '/_app/vehicles/edit/$id': {
      id: '/_app/vehicles/edit/$id'
      path: '/edit/$id'
      fullPath: '/vehicles/edit/$id'
      preLoaderRoute: typeof AppVehiclesEditIdRouteImport
      parentRoute: typeof AppVehiclesRoute
    }
    '/_app/financial/transactions/$id': {
      id: '/_app/financial/transactions/$id'
      path: '/$id'
      fullPath: '/financial/transactions/$id'
      preLoaderRoute: typeof AppFinancialTransactionsIdRouteImport
      parentRoute: typeof AppFinancialTransactionsRoute
    }
    '/_app/employees/edit/$id': {
      id: '/_app/employees/edit/$id'
      path: '/edit/$id'
      fullPath: '/employees/edit/$id'
      preLoaderRoute: typeof AppEmployeesEditIdRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/clients/edit/$id': {
      id: '/_app/clients/edit/$id'
      path: '/edit/$id'
      fullPath: '/clients/edit/$id'
      preLoaderRoute: typeof AppClientsEditIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsIdRoute: typeof AppClientsIdRoute
  AppClientsNewRoute: typeof AppClientsNewRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppClientsEditIdRoute: typeof AppClientsEditIdRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsIdRoute: AppClientsIdRoute,
  AppClientsNewRoute: AppClientsNewRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppClientsEditIdRoute: AppClientsEditIdRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppEmployeesRouteChildren {
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
  AppEmployeesNewRoute: typeof AppEmployeesNewRoute
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
  AppEmployeesEditIdRoute: typeof AppEmployeesEditIdRoute
}

const AppEmployeesRouteChildren: AppEmployeesRouteChildren = {
  AppEmployeesIdRoute: AppEmployeesIdRoute,
  AppEmployeesNewRoute: AppEmployeesNewRoute,
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
  AppEmployeesEditIdRoute: AppEmployeesEditIdRoute,
}

const AppEmployeesRouteWithChildren = AppEmployeesRoute._addFileChildren(
  AppEmployeesRouteChildren,
)

interface AppFinancialTransactionsRouteChildren {
  AppFinancialTransactionsIdRoute: typeof AppFinancialTransactionsIdRoute
  AppFinancialTransactionsIndexRoute: typeof AppFinancialTransactionsIndexRoute
}

const AppFinancialTransactionsRouteChildren: AppFinancialTransactionsRouteChildren =
  {
    AppFinancialTransactionsIdRoute: AppFinancialTransactionsIdRoute,
    AppFinancialTransactionsIndexRoute: AppFinancialTransactionsIndexRoute,
  }

const AppFinancialTransactionsRouteWithChildren =
  AppFinancialTransactionsRoute._addFileChildren(
    AppFinancialTransactionsRouteChildren,
  )

interface AppFinancialRouteChildren {
  AppFinancialBillsRoute: typeof AppFinancialBillsRoute
  AppFinancialTransactionsRoute: typeof AppFinancialTransactionsRouteWithChildren
  AppFinancialIndexRoute: typeof AppFinancialIndexRoute
}

const AppFinancialRouteChildren: AppFinancialRouteChildren = {
  AppFinancialBillsRoute: AppFinancialBillsRoute,
  AppFinancialTransactionsRoute: AppFinancialTransactionsRouteWithChildren,
  AppFinancialIndexRoute: AppFinancialIndexRoute,
}

const AppFinancialRouteWithChildren = AppFinancialRoute._addFileChildren(
  AppFinancialRouteChildren,
)

interface AppPurchasesRouteChildren {
  AppPurchasesIdRoute: typeof AppPurchasesIdRoute
  AppPurchasesNewRoute: typeof AppPurchasesNewRoute
  AppPurchasesIndexRoute: typeof AppPurchasesIndexRoute
}

const AppPurchasesRouteChildren: AppPurchasesRouteChildren = {
  AppPurchasesIdRoute: AppPurchasesIdRoute,
  AppPurchasesNewRoute: AppPurchasesNewRoute,
  AppPurchasesIndexRoute: AppPurchasesIndexRoute,
}

const AppPurchasesRouteWithChildren = AppPurchasesRoute._addFileChildren(
  AppPurchasesRouteChildren,
)

interface AppSalesRouteChildren {
  AppSalesIdRoute: typeof AppSalesIdRoute
  AppSalesNewRoute: typeof AppSalesNewRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
}

const AppSalesRouteChildren: AppSalesRouteChildren = {
  AppSalesIdRoute: AppSalesIdRoute,
  AppSalesNewRoute: AppSalesNewRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
}

const AppSalesRouteWithChildren = AppSalesRoute._addFileChildren(
  AppSalesRouteChildren,
)

interface AppVehiclesRouteChildren {
  AppVehiclesIdRoute: typeof AppVehiclesIdRoute
  AppVehiclesNewRoute: typeof AppVehiclesNewRoute
  AppVehiclesIndexRoute: typeof AppVehiclesIndexRoute
  AppVehiclesEditIdRoute: typeof AppVehiclesEditIdRoute
}

const AppVehiclesRouteChildren: AppVehiclesRouteChildren = {
  AppVehiclesIdRoute: AppVehiclesIdRoute,
  AppVehiclesNewRoute: AppVehiclesNewRoute,
  AppVehiclesIndexRoute: AppVehiclesIndexRoute,
  AppVehiclesEditIdRoute: AppVehiclesEditIdRoute,
}

const AppVehiclesRouteWithChildren = AppVehiclesRoute._addFileChildren(
  AppVehiclesRouteChildren,
)

interface AppRouteChildren {
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppEmployeesRoute: typeof AppEmployeesRouteWithChildren
  AppFinancialRoute: typeof AppFinancialRouteWithChildren
  AppPurchasesRoute: typeof AppPurchasesRouteWithChildren
  AppSalesRoute: typeof AppSalesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppVehiclesRoute: typeof AppVehiclesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientsRoute: AppClientsRouteWithChildren,
  AppEmployeesRoute: AppEmployeesRouteWithChildren,
  AppFinancialRoute: AppFinancialRouteWithChildren,
  AppPurchasesRoute: AppPurchasesRouteWithChildren,
  AppSalesRoute: AppSalesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppVehiclesRoute: AppVehiclesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
